### ISSUE TITLE
load & viz whales, seabirds and turtles

### ISSUE THREAD

**Issue by bbest** [CalCOFI/workflows#9]
Data: 

- [x] [Bird and Mammal Census (CalCOFI, NMFS, CPR)](https://oceaninformatics.ucsd.edu/datazoo/catalogs/ccelter/datasets/255)
  - destination: [whales-seabirds-turtles](https://drive.google.com/open?id=1-7kUb-JCA_DDr6OJ0f4merFyoIv97j1d&authuser=ben%40ecoquants.com&usp=drive_fs)/bird-mammal-census
- [ ] seabirds [ERDDAP - search: 'seabird calcofi'](https://oceanview.pfeg.noaa.gov/erddap/search/index.html?page=1&itemsPerPage=1000&searchFor=seabird+calcofi)
  - destination: [whales-seabirds-turtles](https://drive.google.com/open?id=1-7kUb-JCA_DDr6OJ0f4merFyoIv97j1d&authuser=ben%40ecoquants.com&usp=drive_fs)/...
- [ ] whales [ERDDAP - search: 'whale'](https://oceanview.pfeg.noaa.gov/erddap/search/index.html?page=1&itemsPerPage=1000&searchFor=whale)
  - destination: [whales-seabirds-turtles](https://drive.google.com/open?id=1-7kUb-JCA_DDr6OJ0f4merFyoIv97j1d&authuser=ben%40ecoquants.com&usp=drive_fs)/...
- [ ] turtles ?
- [ ] [OBIS-SEAMAP Dataset - CalCOFI and NMFS Seabird and Marine Mammal Observation Data, 1987-2006](https://seamap.env.duke.edu/dataset/507/html)
  - Seabirds | 58,250
  - Marine mammals: 5,326
  - Sea turtles: 13
  - Rays and sharks: 45
  - Other species: 7,071
  - Total: 70,705
  - destination: [whales-seabirds-turtles](https://drive.google.com/open?id=1-7kUb-JCA_DDr6OJ0f4merFyoIv97j1d&authuser=ben%40ecoquants.com&usp=drive_fs)/...

Next steps:
- [ ] Which of the above are redundant and skippable over first one?
- [ ] add `README.md` per [README - FAQ on Publishing Data Packages | Frictionless Data](https://frictionlessdata.io/blog/2016/04/20/publish-faq/#readme) inside each folder:
  - # Dataset Title
  - ## Introduction
    - Source URL:
    - Date downloaded:
  - ## Data
  - ## Preparation
  - ## License
    - Citation:
- [ ] describe status of reading in file with `oceano-bottle.Rmd`

**Comment by bbest** [comment]
- whales-seabirds-turtles

* [Datazoo](https://oceaninformatics.ucsd.edu/datazoo/catalogs/ccelter/datasets/255)

Next steps:


- add README inside 

- add to this issue: source and destination

**Comment by bbest** [comment]
Looking at OBIS-SEAMAP (by Ei Fujioka)

![image](https://user-images.githubusercontent.com/2837257/158688175-debfb1f1-2f50-458b-a5b8-f88d7973f128.png)

https://seamap.env.duke.edu/dataset/507

![image](https://user-images.githubusercontent.com/2837257/158688488-ef82a189-98d5-4ba9-b66f-999086c66b42.png)

**Comment by bbest** [comment]
## Next Steps

- [ ] Build the tracklines from Start and Stop Lon/Lat locations
- [ ] 1. **Map** of observations given a taxa, optionally with track lines, using a function (like OBIS-SEAMAP above)
- [ ] 2. **Timeseries plot** of observations given a taxa over time, optionally with some standardization of effort, like mentioned below...

- After selecting transects for AOI, show me the presence of a species observed over time?
  - What times was there observation? How much
  - How many observations of the species?
  - Sightings per unit effort (SPUE)
    - What's a "unit of effort"? Perhaps a transect, or better yet length of transect, eg 10 km or unit time of observation.

See Santora, J. A., and W. J. Sydeman. 2015. [Persistence of hotspots and variability of seabird species richness and abundance in the southern California Current](http://dx.doi.org/10.1890/ES14-00434.1). Ecosphere 6(11):214:

> Integrating seabirdobservations with station data requires a grid-based approach to resolve spatially explicit timeseries that account for survey effort over time. Allshipboard tracklines, indexed by 3 km intervals(Yen et al. 2006; Fig. 1), was linked to a GIS, as wehave done for other studies in the CCE (Santoraet al. 2011a, b, 2012a, b). The extent of theshipboard trackline (total survey effort) andCalCOFI sampling stations determined the ex-tent and size of grid cells. This was accomplishedusing the create fishnet command in ArcView toproject the individual 3km sampling points ontoa grid with cells size of 0.78 3 0.78 (;4500 km2).The size of cells was chosen to account for totaltrackline effort (Fig. 1) and to reflect the layout ofthe CalCOFI hydrographic and biological sam-pling stations (Fig. 1) in order to permit futureintegration with those data sets. The grid processresolved the location of consistently sampledcells during 1987–2012 with 45 and 48 cells inspring and summer, respectively (Fig. 1). 
> 
> (17) (PDF) Persistence of hotspots and variability of seabird species richness and abundance in the southern California Current. Available from: https://www.researchgate.net/publication/283799672_Persistence_of_hotspots_and_variability_of_seabird_species_richness_and_abundance_in_the_southern_California_Current [accessed Mar 31 2022].
>
> We standardized sampling effort by assessingthe number of times the ship visited a cell and theamount of survey effort collected within that cell,relative to all cells in a given season over theentire length of the time series (Santora and Veit2013). To determine a threshold to use as a cutoff, we calculated the mean 6 SD of cell visitsand effort per season, then omitted all effort lessthan 1 SD below the mean. 
>
> (17) (PDF) Persistence of hotspots and variability of seabird species richness and abundance in the southern California Current. Available from: https://www.researchgate.net/publication/283799672_Persistence_of_hotspots_and_variability_of_seabird_species_richness_and_abundance_in_the_southern_California_Current [accessed Mar 31 2022].

**Comment by cdobbelaere** [comment]
updated transect lines for all CalCOFI cruises:
<img width="656" alt="Screen Shot 2022-04-06 at 1 58 47 PM" src="https://user-images.githubusercontent.com/69017359/162069977-dd41c147-95b5-4f60-97ef-f3bbc12bc48b.png">

transects filtered by AOI (CINMS):
<img width="647" alt="Screen Shot 2022-04-06 at 1 58 55 PM" src="https://user-images.githubusercontent.com/69017359/162069990-3a0f5948-fd45-46d5-9b23-d7475ebbb485.png">

**Comment by bbest** [comment]
Next steps:

- [ ] create inferred segments between ones already created, but separate them with a field or something representing "OFF effort"

**Comment by bbest** [comment]
## TODO: get original "on effort" segments
- Depends on when observers are there

Original [Bird and Mammal Census (CalCOFI, NMFS, CPR)](https://oceaninformatics.ucsd.edu/datazoo/catalogs/ccelter/datasets/255) is missing start/stop times of on effort segments. We see "a time"  in [ERDDAP - Farallon Institute CalCOFI Seabirds: Transect Log - Data Access Form](https://oceanview.pfeg.noaa.gov/erddap/tabledap/CAC_FI_SBAS_tr.html), but not start/stop for being able to reconstruct segments. Ugh.

time | latitude | longitude | gis_key | transect | bin | date | datedate | numeric_time | length_km | width_km | area_km2 | cruise | season | core
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2019-07-19T06:24:00Z | 33.043694 | -120.22274 | CAC20190719F1 | 1 | 1 | 190719 | 7/19/2019 | 624.0 | 3.018 | 0.3 | 0.905 | CAC2019_7 | Summer | 1
2019-07-19T11:29:00Z | 32.917522 | -120.498634 | CAC20190719F10 | 3 | 10 | 190719 | 7/19/2019 | 1129.0 | 3.009 | 0.3 | 0.903 | CAC2019_7 | Summer | 1
2019-07-19T11:39:00Z | 32.90367 | -120.52781 | CAC20190719F11 | 3 | 11 | 190719 | 7/19/2019 | 1139.0 | 3.016 | 0.3 | 0.905 | CAC2019_7 | Summer | 1
2019-07-19T11:48:00Z | 32.889923 | -120.556915 | CAC20190719F12 | 3 | 12 | 190719 | 7/19/2019 | 1148.0 | 2.993 | 0.3 | 0.898 | CAC2019_7 | Summer | 1

**Comment by bbest** [comment]
Closing as superseded (2026-09-09 triage of the CalCOFI GitHub, ahead of a new project board). Seabirds and marine mammals are released as `farallon_bird-mammal` (https://calcofi.io/datasets/farallon_bird-mammal/) and drawn by the Explorer; cetaceans (`sio_cetacean-sightings`) are a listed holding.
